"""add parent_id to messages for thread replies

Revision ID: 55be1b22b0ea
Revises: ca9481fbf6e9
Create Date: 2026-06-18 22:03:29.192527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55be1b22b0ea'
down_revision: Union[str, None] = 'ca9481fbf6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('parent_id', sa.BigInteger(), nullable=True))
    op.create_index('idx_messages_parent_id', 'messages', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index('idx_messages_parent_id', table_name='messages')
    op.drop_column('messages', 'parent_id')
    # ### end Alembic commands ###
